import{a as i,S as f,i as c}from"./assets/vendor-BNibzuFn.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&l(o)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();i.defaults.baseURL="https://pixabay.com/api/";i.defaults.params={key:"52056130-db9fbcb72f3bb5afb21255a47",image_type:"photo",orientation:"horizontal",safesearch:!0};function m(a){return i.get("",{params:{q:a}}).then(s=>s.data.hits)}const p=document.querySelector(".gallery"),d=document.querySelector(".loader");let n=null;function y(a){const s=a.map(t=>`<div class="card">
              <a href=${t.largeImageURL}><img src="${t.webformatURL}" alt="${t.tags}" class="gallery-images"></a>
              <div class="info">
                <p class="name">Likes<span class="value">${t.likes}</span></p>
                <p class="name">Views<span class="value">${t.views}</span></p>
                <p class="name">Comments<span class="value">${t.comments}</span></p>
                <p class="name">Downloads<span class="value">${t.downloads}</span></p>
              </div>
            </div>`).join("");p.insertAdjacentHTML("beforeend",s),n?n.refresh():n=new f(".gallery a",{captionsData:"alt",captionDelay:250})}function h(){p.innerHTML=""}function g(){d.classList.add("is-visible")}function b(){d.classList.remove("is-visible")}const u=document.querySelector(".search-input"),v=document.querySelector(".form");v.addEventListener("submit",a=>{if(a.preventDefault(),h(),!u.value){alert("Введіть слово для пошуку");return}g();const s=u.value.toLowerCase();m(s).then(t=>{if(t.length===0){c.error({title:"Oops",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t)}).catch(t=>{console.error(t),c.error({title:"Error",message:"Something went wrong. Try again later!",position:"topRight"})}).finally(()=>{b()})});
//# sourceMappingURL=index.js.map
